version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TempestBot"
s3_prefix = "TempestBot"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false
