name: Put application commands
on:
  push:
    branches:
      - main
    paths:
      - scripts/commands/commands.py
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install requests boto3 --no-input
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - shell: bash
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        working-directory: scripts/commands
        run: |
          python3 commands.py
